development:
  mailer_user_name: <%= ENV['MAILER_USER_NAME'] %>
  mailer_password: <%= ENV['MAILER_PASSWORD'] %>
  mailer_address: <%= ENV['MAILER_ADDRESS'] %>
  mailer_domain: <%= ENV['MAILER_DOMAIN'] %>
  mailer_port: <%= ENV['MAILER_PORT'] %>
  default_email_address: 'pmarclay-a95220@inbox.mailtrap.io'

test:
  mailer_user_name: <%= ENV['MAILER_USER_NAME'] %>
  mailer_password: <%= ENV['MAILER_PASSWORD'] %>
  mailer_address: <%= ENV['MAILER_ADDRESS'] %>
  mailer_domain: <%= ENV['MAILER_DOMAIN'] %>
  mailer_port: <%= ENV['MAILER_PORT'] %>

